### ISSUE TITLE
Show hands 

### ISSUE THREAD

**Issue by MaguirePool** [Roblox-Thot/VapeThotMod#2]
**Describe the bug**
After you die with this option enabled your hands look like a disabled person lol

**To Reproduce**
use "ShowHands"

**Expected behavior**
It should look like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/88889733/235383639-8a7276ec-3f1c-4205-9aeb-40d65ea74b51.png)

**Executor (please complete the following information):**
 - Name: Krnl
 - Version: Latest

**Additional context**

If you disable and enable the option then it will be normal

**Comment by Roblox-Thot** [comment]
I think that might be the avatar package you have on?

because when I respawn it looks fine it just swaps the arms to what ever package I have equipped on my avatar
